- name: Copy Casssandra configuration file
  template:
    src: cassandra.yaml.j2
    dest: "{{ cassandra_config_file_path }}"
    backup: yes
  register: cassandra_init_config_reg
  tags: cassandra-config

- block: # Clean up system configuration
  - name: Stop cassandra for Reload configuration
    systemd:
      name: cassandra
      state: stopped
  - find:
      path: "{{ cassandra_home }}/data/system"
      file_type: directory
    register: system_directories_reg
  - name: Cleanup old configuration and data of Cassandra
    file:
      path: "{{ item.path }}"
      state: absent
    with_items:
      - "{{ system_directories_reg.files }}"
  when: cassandra_init_config_reg is changed
  tags: cassandra-config

- name: Start Cassandra service
  systemd:
    name: "{{ cassandra_service_name }}"
    state: restarted
    enabled: yes
  when: cassandra_init_config_reg is changed
  tags: cassandra-config

- block: # State of Cluster
  - name: Wait for Cassandra service is started
    wait_for:
      host: "{{ ansible_default_ipv4.address }}"
      port: 7000
      delay: 30
  - name: Prepare nodetool for run status
    pause:
      seconds: 10
  - name: Check node status
    shell: nodetool status
    register: nodestat_reg
  - name: Node status
    debug: 
     msg: "{{ nodestat_reg.stdout.split('\n') }}"
  tags: cassandra-config
