- name: Copy Casssandra configuration file
  template:
    src: "{{ cassandra_host_config_file_path }}"
    dest: "{{ cassandra_config_file_path }}"
  register: cassandra_init_config_reg
  when: cassandra_config_check_reg.stat.exists
  notify: reload cassandra service
  tags: cassandra-config


#  when: cassandra_init_config_reg is changed 

- block: # Clean up system configuration
  - name: Stop cassandra for Reload configuration
    systemd:
      name: cassandra
      state: stopped

  - find:
      path: "{{ cassandra_system_data_path }}"
      file_type: directory
    register: system_directories_reg

  - name: Cleanup old configuration and data of Cassandra
    file:
      path: "{{ item.path }}"
      state: absent
    with_items:
      - "{{ system_directories_reg.files }}"
  when: cassandra_init_config_reg is changed
  tags: cassandra-config