- name: Copy Casssandra configuration file
  template:
    src: "{{ cassandra_host_config_file_path }}"
    dest: "{{ cassandra_config_file_path }}"
    backup: yes
  register: cassandra_init_config_reg
  when: cassandra_config_check_reg.stat.exists
#   notify: reload cassandra service
  tags: cassandra-config

- block: # Clean up system configuration
  - name: Stop cassandra for Reload configuration
    systemd:
      name: cassandra
      state: stopped
  - find:
      path: "{{ cassandra_system_data_path }}"
      file_type: directory
    register: system_directories_reg
  - name: Cleanup old configuration and data of Cassandra
    file:
      path: "{{ item.path }}"
      state: absent
    with_items:
      - "{{ system_directories_reg.files }}"
  when: cassandra_init_config_reg is changed
  tags: cassandra-config

- name: Start Cassandra Seed service
  systemd:
    name: "{{ cassandra_service_name }}"
    state: restarted
    enabled: yes
  tags: cassandra-config

- block: # State of Cluster
  - name: Wait for start seed cluster service
    pause:
      minutes: 1
  - name: Check node status
    shell: nodetool status
    register: nodestat_reg
  - debug: 
     msg: "{{ nodestat_reg.stdout.split('\n') }}"
  tags: cassandra-config
