---
- name: Download Jolokia source binary
  get_url:
    url: "{{ cassandra_jolokia2_url }}"
    dest: "{{ cassandra_lib_path }}"
    owner: root
    group: root
    mode: 0644
  notify: Restart cassandra service

- name: Append Cassandra env for apply Jolikia library
  lineinfile:
    dest: "{{ cassandra_env_config_file_path }}"
    regexp: '^JVM_OPTS'
    insertafter: EOF
    line: JVM_OPTS="$JVM_OPTS $JVM_EXTRA_OPTS -javaagent:$CASSANDRA_HOME/lib/jolokia-jvm-{{ cassandra_jolokia2_plugins.version }}-agent.jar=port={{ cassandra_jolokia2_plugins.listen_port }},host={{ cassandra_jolokia2_plugins.listen_host }}"
    state: present
  notify: Restart cassandra service
