---
- name: Detect version of Cassandra
  shell: "apt list --installed | grep cassandra  | awk '{print $2}'"
  register: cassandra_version_reg

# Fix cqlsh
- name: Fix cqlsh when version of Cassandra less than 3.9
  include_tasks: cassandra_fix_cqlsh.yml
  when: cassandra_version_reg.stdout|int < 3.9

- name: Copy Keystore files to Cassandra
  copy:
    src: "{{ cassandra_host_keystore_path }}"
    dest: "{{ cassandra_config_base_path }}"
    mode: 0640
    directory_mode: 0755
    owner: cassandra
    group: cassandra
  when: 
    - cassandra_keystore_check_reg.stat.isdir is defined
    - cassandra_keystore_check_reg.stat.isdir
  tags: cassandra-config

- name: Prepare directories for Cassandra
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: cassandra
    group: cassandra
  with_items:
    - "{{ cassandra_hints_directory }}"
    - "{{ cassandra_data_file_directories }}"
    - "{{ cassandra_commitlog_directory }}"
    - "{{ cassandra_saved_caches_directory }}"
  tags: cassandra-config

- name: Copy cassandra-rackdc.properties file
  template: 
    src: cassandra-rackdc.properties.j2
    dest: "{{ cassandra_rackdc_config_file_path }}"
  register: cassandra_rackdc_init_config_reg
  tags: cassandra-config

- name: Copy cassandra.yaml file
  template:
    src: cassandra.yaml.j2
    dest: "{{ cassandra_config_file_path }}"
  register: cassandra_init_config_reg
  tags: cassandra-config

- block: # Clean up system configuration
  - name: Check for Cassandra is initialed
    find:
      path: "{{ item }}/system"
      file_type: directory
    with_items:
      - "{{ cassandra_data_file_directories }}"
    register: system_directories_reg
  - name: Unjoin Node before reconfiguration
    shell: nodetool decommission
    when: system_directories_reg.results[0].files != []
  - name: Stop cassandra for Reload configuration
    systemd:
      name: "{{ cassandra_service_name }}"
      state: stopped
  - name: Cleanup system configuration schemas of Cassandra
    file:
      path: "{{ item }}/system"
      state: absent
    with_items:
      - "{{ cassandra_data_file_directories }}"
  - name: Cleanup commitlog configuration of Cassandra
    file:
      path: "{{ cassandra_commitlog_directory }}"
      state: absent
  - name: Cleanup caches configuration of Cassandra
    file:
      path: "{{ cassandra_saved_caches_directory }}"
      state: absent
  when: cassandra_rackdc_init_config_reg is changed or
        cassandra_init_config_reg is changed
  tags: cassandra-config

- name: Start Cassandra service
  systemd:
    name: "{{ cassandra_service_name }}"
    state: restarted
    enabled: yes
  when: cassandra_rackdc_init_config_reg is changed or 
        cassandra_init_config_reg is changed
  tags: cassandra-config

- block: # State of Cluster
  - name: Wait for Cassandra service is started
    wait_for:
      host: "{{ ansible_default_ipv4.address }}"
      port: 7000
      delay: 30
  - name: Prepare nodetool for run status
    pause:
      seconds: 10
  - name: Check node status
    shell: nodetool status
    register: nodestat_reg
  - name: Node status
    debug: 
     msg: "{{ nodestat_reg.stdout.split('\n') }}"
  tags: cassandra-config

- block:
  - name: Install Jokolia2 metric
    include_tasks: cassandra_plugins.yml
  tags: test
  when: cassandra_jolokia2_plugins