- name: Install Apache Cassandra
  apt:
    name: "{{ cassandra_packages }}"
    state: present
    update_cache: yes

- name: Install Jokolia2 metric
  include_tasks: cassandra_plugins.yml
  when: cassandra_jolokia2_plugins.enabled == true