---
# tasks file for ansible-cassandra
- name: Include OS vars
  include_vars: "{{ ansible_os_family }}.yml"

- include_tasks: cassandra_pre.yml
- include_tasks: cassandra_install.yml
  
- block:
  - include_tasks: cassandra_search_config.yml
  - import_tasks: cassandra_post.yml
  tags: cassandra-config
  