---
# tasks file for ansible-cassandra
- name: Include OS vars
  include_vars: "{{ ansible_distribution }}.yml"

- include_tasks: cassandra_pre.yml
- include_tasks: cassandra_install.yml
  
- include_tasks: cassandra_post.yml
  tags: cassandra-config
